import pandas as pd

# Creating the 30-day learning plan for Excel and PowerPoint in a DataFrame
data = {
    "Day": list(range(1, 31)),
    "Excel Learning Objective": [
        "Excel interface, workbook basics",
        "Data entry and formatting",
        "Basic formulas (SUM, AVERAGE, COUNT)",
        "Sorting and filtering",
        "Conditional formatting",
        "Data validation rules",
        "Basic charts (bar, line, pie)",
        "IF function",
        "VLOOKUP function",
        "CONCATENATE and TEXT functions",
        "Pivot tables",
        "Conditional formatting for KPIs",
        "Advanced charts (combo, waterfall)",
        "Creating dashboards",
        "Data analysis tools (Goal Seek, Solver)",
        "INDEX and MATCH functions",
        "Cleaning and analyzing datasets",
        "Introduction to macros",
        "Workbook protection and sharing",
        "Financial functions (NPV, IRR)",
        "Advanced filtering",
        "Text functions (LEFT, RIGHT, LEN)",
        "Working with large datasets",
        "Advanced pivot tables",
        "Power Query basics",
        "Using slicers and timelines",
        "Introduction to VBA",
        "Data visualization best practices",
        "Reviewing and optimizing spreadsheets",
        "Final Excel and PowerPoint project"
    ],
    "Excel Task": [
        "Create an employee attendance tracker.",
        "Enter and format product inventory data.",
        "Calculate total monthly sales for each product.",
        "Sort and filter employee data by department.",
        "Highlight overdue invoices in a payment tracker.",
        "Create input rules for expense reports.",
        "Create a sales performance chart.",
        "Flag low-performing products using conditions.",
        "Fetch product details from a master database.",
        "Combine employee names and designations.",
        "Summarize sales data by region and product.",
        "Highlight KPIs exceeding targets.",
        "Visualize revenue trends.",
        "Design an interactive sales dashboard.",
        "Optimize pricing strategy for maximum profit.",
        "Extract data for a custom report.",
        "Clean and analyze a customer feedback dataset.",
        "Automate repetitive tasks in a payroll sheet.",
        "Protect and share a financial report.",
        "Calculate project profitability.",
        "Use advanced filters to extract specific data.",
        "Extract specific information from customer names.",
        "Analyze sales data from multiple sources.",
        "Create pivot charts for a financial report.",
        "Import and clean data from multiple sources.",
        "Create interactive slicers for dashboards.",
        "Write a basic macro for automating tasks.",
        "Redesign charts for better clarity.",
        "Audit and optimize formulas in workbooks.",
        "Combine Excel analysis and PowerPoint slides."
    ],
    "PowerPoint Learning Objective": [
        "PowerPoint interface, slide creation",
        "Adding text and images",
        "Applying slide themes and layouts",
        "Creating SmartArt diagrams",
        "Adding slide transitions",
        "Using tables in presentations",
        "Embedding Excel charts",
        "Animations basics",
        "Master slides and templates",
        "Adding hyperlinks",
        "Embedding videos",
        "Presenter view",
        "Exporting presentations as videos",
        "Reviewing presentations",
        "Adding navigation buttons",
        "Advanced animations",
        "Designing infographics",
        "Custom slide designs",
        "Collaborating on presentations",
        "Adding interactive elements",
        "Creating summary slides",
        "Combining visual elements",
        "Formatting for impact",
        "Embedding external links",
        "Finalizing presentations",
        "Exporting to PDF",
        "Creating an end-to-end presentation",
        "Integrating feedback",
        "Practicing presentations",
        "Presenting the project"
    ],
    "PowerPoint Task": [
        "Create a company introduction slide.",
        "Create a slide with the company mission and vision.",
        "Design slides using the company’s branding colors.",
        "Design an organizational hierarchy chart.",
        "Add transitions to a company presentation.",
        "Add a table comparing product sales by region.",
        "Insert the sales chart into a PowerPoint slide.",
        "Animate key points in a product presentation.",
        "Create a reusable corporate presentation template.",
        "Link slides to external company resources.",
        "Add a training video to a presentation.",
        "Practice presenting using Presenter View.",
        "Export a product demo presentation as a video.",
        "Refine the earlier product pitch presentation.",
        "Create a menu-based interactive presentation.",
        "Animate product features for a sales demo.",
        "Create a sales infographic using charts and shapes.",
        "Customize a slide for a new service launch.",
        "Use comments and track changes for a team project.",
        "Add navigation buttons and links to resources.",
        "Summarize a department’s performance in 5 slides.",
        "Use charts, images, and text for a marketing report.",
        "Improve the readability of slides with formatting.",
        "Link to external documents and websites.",
        "Review and finalize a company project presentation.",
        "Save the presentation as a professional PDF.",
        "Prepare a full project presentation.",
        "Incorporate team feedback into the presentation.",
        "Rehearse the final presentation.",
        "Present the final report on the company’s progress."
    ]
}

# Converting to DataFrame
learning_plan = pd.DataFrame(data)

# Saving to an Excel file
file_path = "/mnt/data/Excel_PPT_30_Day_Learning_Plan.xlsx"
learning_plan.to_excel(file_path, index=False)

file_path
